name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            # Welcome to the Project!
            Thank you for opening your first issue. We appreciate your contribution and will review it shortly.
          pr-message: |
            # Welcome to the Project!
            Thank you for submitting your first pull request. We appreciate your contribution and will review it shortly.

